### ISSUE TITLE
行间代码样式被主题修改

### ISSUE THREAD

**Issue by zhangyaochn** [LuRenJiasWorld/WP-Editor.md#435]
在编辑器中行间代码显示正常。发布后仅看到代码字体改变。没有看到颜色背景。能自定义行间代码样式吗？

**Comment by LuRenJiasWorld** [comment]
你指的是`text`这种样式吗？前台显示文本的样式是根据主题决定的，如果需要进行自定义修改，直接在主题自定义面板中加入所需的CSS样式即可。

后续版本可能会加入强制覆盖主题样式的功能，但是目前只能手动操作修改样式。

**Comment by trail-coffee** [comment]
Fix first line in multi-line:
```
 code
code
```
to
```
code
code
```

Add background box with rounded corners to `text`


**style.css**

```
code {
	background: #eee;
	border-radius: 3px;
}

code:not([class]) {
	padding: 3px;
}
```

**Comment by LuRenJiasWorld** [comment]
> Fix first line in multi-line:
> 
> ```
>  code
> code
> ```
> 
> to
> 
> ```
> code
> code
> ```
> 
> Add background box with rounded corners to `text`
> 
> **style.css**
> 
> ```
> code {
> 	background: #eee;
> 	border-radius: 3px;
> }
> 
> code:not([class]) {
> 	padding: 3px;
> }
> ```

Sorry I can't get what do you mean, Is this a new issue? 
If it is, please open an individual issue for me to track it. 
Thanks.

**Comment by trail-coffee** [comment]
That’s how to get a background on inline code and style it, that was my understanding of the original question for this issue.

I added the multi-line code first line indent, because that’s another problem in WP. The css fixes that too.

**Comment by LuRenJiasWorld** [comment]
> That’s how to get a background on inline code and style it, that was my understanding of the original question for this issue.
> 
> I added the multi-line code first line indent, because that’s another problem in WP. The css fixes that too.

This issue is about theme overriding the plugin's default style. So It might be similar with your advice.

Even though I thought these styles should be implemented in the theme's stylesheets, but many user have mentioned the compatibility issues (including your issue) between this plugin and certain themes, so I think I will add an option for users to override theme's style and use the prebuilt style in the future.

Thanks for your advice, I'll try to implement it.
